### ISSUE TITLE
Old API

### ISSUE THREAD

**Issue by mikeaustin** [lelandrichardson/enzyme-example-mocha#11]
Looks like this example is using the old API? FYI, learning Mocha has been so difficult because of API non-backwards compatibility in other libraries like jsdom.

This project is from a direct link from enzyme:
https://github.com/airbnb/enzyme/blob/master/docs/guides/jsdom.md

**Comment by jsmey** [comment]
I submitted PR https://github.com/lelandrichardson/enzyme-example-mocha/pull/12 for this
