### ISSUE TITLE
TypeError: Cannot read property 'equal' of undefined

### ISSUE THREAD

**Issue by HideyaSwider** [lelandrichardson/enzyme-example-mocha#5]
Hi,

That error occurs when I run these tests (occurs as well when I use shallow):

``` javascript
it("length is = 1", function() {
    expect(render(<Component />).find('.body').length).to.equal(1);
});

it("It has a footer", function() {
    const wrapper = shallow(<Component />);
    expect(wrapper.find('img')).to.have.length(1);
});

```

.setup.js file is the same and I have all of the dependencies installed.

Any tips to get this working?

Thanks.

**Comment by HideyaBenAbderrahmen** [comment]
Using expect instead of chai's expect.

**Comment by yokesharun** [comment]
Your question is indexed in google but there is no answers or issues solve so I'm attaching the solution from StackOverflow : https://stackoverflow.com/questions/39926517/typeerror-cannot-read-property-equal-of-undefined
